import 'package:json_annotation/json_annotation.dart';

part 'student.g.dart';

@JsonSerializable()
class Student {
  final String id; // Firebase UID or document ID
  final String? studentId; // ID generated by server
  final String fullName;
  final String phoneNumber;
  final String email;
  final String? profileImage;

  Student({
    this.profileImage,
    required this.id,
    required this.fullName,
    required this.phoneNumber,
    required this.email,
    this.studentId,
  });

  factory Student.fromJson(Map<String, dynamic> json) =>
      _$StudentFromJson(json);
  Map<String, dynamic> toJson() => _$StudentToJson(this);

  // CopyWith method
  Student copyWith({
    String? id,
    String? fullName,
    String? phoneNumber,
    String? email,
    String? studentId,
    String? profileImage,
  }) {
    return Student(
      id: id ?? this.id,

      fullName: fullName ?? this.fullName,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      email: email ?? this.email,
      studentId: studentId ?? this.studentId,
      profileImage: profileImage ?? this.profileImage,
    );
  }
}
